version: "3"
services:
   randomizer-service:
      hostname: randomizer-service
      image: tomee
      build: ./service 
      image: randomizer-service      
      ports:
      - "9080:8080"
      networks:
      - host    
   randomizer-ui:
      hostname: randomizer-ui
      image: tomee
      build: ./ui
      image: randomizer-ui
      ports:
      - "9090:8080"
      networks:
      - host
      environment:
      - RANDOMIZER_SERVER_NAME=randomizer-service
      - RANDOMIZER_SERVER_PORT=8080
networks:
   host: